name: Add chromatic comment
on: pull_request
jobs:
  chromatic-review-url:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: |
            👋 @{{ author }}
            Review your pull request on chromatic: https://www.chromatic.com/pullrequest?appId=63ee57592a53ae7413d27e43&number={{ payload.number }}
